add_demo("demo_ing_gl_pure_app", {"SailIng"})
add_demo("demo_ing_gl_basic_app", {"SailIng"})
add_demo("demo_ing_gl_scene_app", {"SailIng"})
add_demo("demo_ing_curve_fit", {"SailIng"})
add_demo("demo_ing_terrain", {"SailIng"})