SHARED_MODULE("SailCu", "SAIL_CU", engine_version)
    add_includedirs("include", { public = true })
    set_languages("c++17", "cuda")
    add_files("src/dummy.cu")
    add_deps("SailBase")
    add_packages("glm", { public = true })
    -- add_rules("sail.cuda")