SHARED_MODULE("SailCu", "SAIL_CU", engine_version)
    add_includedirs("include", { public = true })
    -- add_files("src/**.cu")
    add_files("src/dummy.cu")
    add_deps("SailBase")
    add_packages("glm", { public = true })
    add_rules("sail.cuda")