SHARED_MODULE("SailInno", "SAIL_INNO", engine_version)
    add_includedirs("include", {public = true})
    add_files("src/**.cpp")
    load_lc()
    add_rules("sail.cuda", "lc.lcub")
    add_deps("SailBase")
