package("glm")
    add_versions("1.0.1-sail", "650250979303a649e21f87b5ccd02672af1ea6954b911342ea491f351ceb7122")
    set_homepage("")
    set_description("OpenGL Mathematics (GLM) is a header only C++ mathematics library for graphics software based on the OpenGL Shading Language (GLSL) specifications.")
    add_urls("")
    on_install("windows", function (package)
        os.mkdir(package:installdir())
        -- print("copying glm to " .. package:installdir())
        os.cp(path.join(package:scriptdir(),"glm"), package:installdir("include"))
    end)
package_end()