SHARED_MODULE("SailDummy", "SAIL_DUMMY", engine_version)
    add_includedirs("include", {public = true})
    add_files("src/**.cpp")
    add_deps("SailCore")
    add_deps("external_stb_util", {public = true})
    add_deps("external_tiny_obj_loader_util", {public = true})