rule("web")
    set_extensions(".html", ".css", ".js", ".py")
    on_load(function(target)
        target:set("kind", "object") 
        local targetdir = path.join(target:targetdir(), target:name())
        os.mkdir(targetdir)
        target:set("targetdir", targetdir)
    end)
    on_build_file(function (target, sourcefile, opt)
        os.cp(sourcefile, target:targetdir())
    end)
    on_link(function(target, opt)
        -- nothing to do
    end)
    after_build(function(target, opt)
    end)
    on_run(function(target)
        -- cd to the targetdir
        import("lib.detect.find_tool")
        os.cd(target:targetdir())
        local py = assert(find_tool("python", {check = "--version"}), "python not found!")
        os.vrunv(py.program, {"server.py"})
        os.cd("$(projectdir)")
    end)
rule_end()